# Generated by Django 5.1.1 on 2024-09-28 03:25

import Food_Munch_App.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.CharField(max_length=1000)),
                ('ProductName', models.CharField(max_length=500)),
                ('Cost', models.CharField(max_length=8)),
                ('Quantity', models.CharField(max_length=10)),
                ('OrderDateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentSectionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerName', models.CharField(max_length=50)),
                ('EmailId', models.CharField(max_length=100)),
                ('MobileNumber', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=30)),
                ('State', models.CharField(max_length=30)),
                ('PinCode', models.CharField(max_length=6)),
                ('PaymentMethod', models.CharField(max_length=25)),
                ('CardName', models.CharField(max_length=30)),
                ('CardNumber', models.CharField(max_length=19)),
                ('CardExpiry', models.CharField(max_length=7)),
                ('Cvv', models.CharField(max_length=3)),
                ('PaymentDateTime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantMenuCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemImage', models.ImageField(upload_to='RestaurantMenuCard/')),
                ('ItemName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SignupSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerName', models.CharField(max_length=50)),
                ('MobileNumber', models.CharField(max_length=10, unique=True)),
                ('EmailId', models.CharField(default='', max_length=100, unique=True)),
                ('Password', models.CharField(max_length=50)),
                ('DateOfRegisteration', models.DateTimeField(default=django.utils.timezone.now)),
                ('UserLastUpdate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=500)),
                ('Video_File', models.FileField(upload_to='videos')),
                ('Upload_DateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductImage', models.ImageField(upload_to=Food_Munch_App.models.CategoryProduct)),
                ('ProductName', models.CharField(max_length=250)),
                ('ProductCost', models.CharField(max_length=6)),
                ('ProductQuantity', models.CharField(default=1, max_length=2)),
                ('ProductCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Food_Munch_App.category')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductImage', models.ImageField(upload_to='CartItems/')),
                ('ProductName', models.CharField(max_length=250)),
                ('ProductCost', models.CharField(default='0', max_length=6)),
                ('ProductQuantity', models.CharField(default=1, max_length=2)),
                ('Cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Food_Munch_App.cart')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Food_Munch_App.product')),
            ],
        ),
        migrations.CreateModel(
            name='LoginSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmailId', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=50)),
                ('LoginDateTime', models.DateTimeField(auto_now=True)),
                ('LoginStatus', models.BooleanField(default=True)),
                ('User', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Food_Munch_App.signupsection')),
            ],
        ),
    ]
